---
- name: Bootstrap Main Node
  hosts: main
  become: yes
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090

  tasks:
    - name: download apt key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key 
        state: present
    - name: Add grafana to sources.list
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        filename: grafana
        state: present
    - name: Update apt cache and install Grafana
      ansible.builtin.apt:
        name: grafana
        update_cache: yes
    - name: Ensure Grafana is started and enabled
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: true

    - name: Download Prometheus
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /home/ubuntu
    - name: Extract From Resources
      ansible.builtin.unarchive:
        src:  /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /home/ubuntu
        remote_src: yes
    - name: Create Prom Group
      ansible.builtin.group:
        name: prometheus
        state: present
    - name: Create Prom User
      ansible.builtin.user:
        name: prometheus
        shell: /sbin/nologin
        groups: prometheus
    - name: Create Prom Directories
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        recurse: yes
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        -  /etc/prometheus
        -  /etc/prometheus/rules
        -  /etc/prometheus/rules.d
        -  /etc/prometheus/files_sd
        -  /var/lib/prometheus

    - name: Copy Files
      ansible.builtin.copy:
        src: "{{item}}"
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
        owner: prometheus
        group: prometheus
      loop: 
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool
    - name: Copy Files
      ansible.builtin.copy:
        src: "{{item}}"
        dest: /etc/prometheus/
        remote_src: yes
      loop: 
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries

    - name: Create config file 
      ansible.builtin.template:
       src: prometheus.yml.j2
       dest: /etc/prometheus/prometheus.yml
    - name: Create Systemd File
      ansible.builtin.template:
       src: prometheus.service.j2
       dest: /etc/systemd/system/prometheus.service
    - name: Ensure Prometheus is started
      ansible.builtin.systemd:
        name: prometheus
        state: started
        enabled: true
 
